# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=toor
    volumes: 
      - /Users/antoniotapiamaldonado/Documents/apps/datingapp/postgresdb:/var/lib/postgresql/data